config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/index'

  #To map with user controller
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/contacts/:provider/contact_callback", to:"dashboards#index"
  get "/contacts/failure", to:"dashboards#failure"


  devise_scope :user do

    # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',passwords: 'users/passwords' }
    root 'users/sessions#new'

    # get 'auth/:provider/callback', to: 'sessions#create'

    scope '/users' do
    
      resources :albums do     
        collection do
          get '/my_album', to: "albums#my_album",as: 'my_album'
          get '/friend_album', to: "albums#friend_album",as: 'friend_album'
        end  
        member do
          delete 'destroy_pic'
        end
        
        resources :comments,only: [:index,:destroy,:new,:create] do
          collection do
            post '/remark', to:'comments#remark', as: 'remark'
            post '/comments_remark', to:'comments#comments_remark', as: 'cmts_remark'
          end
          member do
            delete 'comment_destroy', to: 'comments#comment_destroy', as: 'cmts_destroy'
          end
        end
      end

      resources :friends, only: [:index,:show,:destroy] do
        get :notification
        
        collection do
          get '/:token/accept', to:'friends#accept', as: 'accept'
        end
      end
      post 'friends/search', to:'friends#search'
    end
    resources :dashboards, only: :index
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Validations
  validates :comment_name, presence: true

  #Association
  belongs_to :commentable, polymorphic: true, counter_cache: :count
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :get_comment, only: [:destroy]

	#Filters skip
	skip_before_action :verify_authenticity_token, :only => [:remark]

	#Filters
	before_action :get_album, only: [:remark, :comments_remark,:index]	

	#Actions
	def index
		@comment = Comment.new
		@friend = User.find_by(id: @album.user_id)
	end

	def remark
		@comment = @album.comments.build(comment_name: params[:new_comment], user_id: current_user.id)
		@comment.save
		respond_to do |format|
			format.js
		end
	end

	def destroy	
		@comment = @comment.destroy
		respond_to do |format|
			format.js
		end
	end

	def new
	end

	def create
	end

	
	def show	
	end

	def edit 
	end

	def update
	end

	#Private methods
	private
		def get_comment
			@comment = Comment.find(params[:id])
		end

		def get_album
			@album = Album.find_by(id: params[:album_id])
		end
end

app/views/comments/_comment_div.html.erb
<div id="com-<%=current_user.id%>">
  <div class="col-md-12">
    <b><%= current_user.name%></b>
  </div>

  <div class="col-md-9 col-sm-offset-1">
    : <%= @comment.comment_name%>    
  </div>
  
  <div class="col-md-2">
    <% if @comment.user_id == current_user.id %>
      <%= link_to album_comment_path(@album.id,@comment.id), method: :delete, remote: true ,  data: { confirm: 'Sure to delete comment ?'} do %>
      <i class="fa fa-times fa-2x" aria-hidden="true" ></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/destroy.js.erb
$('#comments').find("#com-<%=@comment.id%>").remove()

app/views/comments/index.html.erb
  <div class="col-md-3 ">
    <h3><b>Album-Name</b></h3>
  </div>
  
  <div class="col-md-4">
    <h3><%= @album.album_name %></h3>
    <hr>
  </div>

  <div class="col-md-8 color-ffeecc">
    <% @album.album_images.each do |item|%>
      <div class="col-md-3">
        <%= image_tag item.image_name_url, height: "180px", width: "180px", class: 'img-rounded' %>
      </div>
    <% end %>   
  </div>

  <div class="col-md-4 color-c2d6d6">
    <div class="col-md-1">
      <% if @friend.avatar.present? %>
        <%= image_tag @friend.avatar_url, height: "50px", width: "50px" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <p><%= @friend.name  %></p>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-12">
      <hr><hr>
    </div>

    <div id="comments">
      <% @album.comments.each do |comment| %>
        <% user = User.find_by(id: comment.user_id) %>
          <div id="com-<%=comment.id%>">
            <div class="col-md-12">
              <b><%= user.name%></b>
            </div>
          
            <div class="col-md-9 col-sm-offset-1">
              : <%= comment.comment_name%>
            </div>

            <div class="col-md-2">
              <% if comment.user_id==current_user.id %>
                <%= link_to album_comment_path(@album.id,comment.id) , method: :delete, remote: true ,  data: { confirm: 'Sure to delete comment ?'} do %>
                  <i class="fa fa-times fa-2x" aria-hidden="true" ></i>
                <% end %> 
              <% end %>
            </div>
          </div>
      <% end %>
    </div>

    <%= form_for @comment ,url: remark_album_comments_path(@album.id), method: :post, :html => { :onsubmit => "return false" } do |f| %>  
      <div class="col-md-12">
      <hr><hr>
      </div>
      <div class="col-md-12">
        <%= f.label :comments %>
      </div>

      <%= hidden_field_tag(:user_id, current_user.id) %>
      <%= hidden_field_tag(:album_id, @album.id) %>

      <div class="col-md-12 comment">
        <%= f.text_field :comment_name, required: true, class:"form-control" %>
      </div>
      <div class="col-md-12">
        <%= f.submit "Create New Comment", :onclick => "submit_btn();" %>
      </div>    
    <% end %>
  </div>

app/views/comments/remark.js.erb
$('#comments').append("<%= j render partial: 'comment_div' %>")