config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/index'

  #To map with user controller
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/contacts/:provider/contact_callback", to:"dashboards#index"
  get "/contacts/failure", to:"dashboards#failure"


  devise_scope :user do

    # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',passwords: 'users/passwords' }
    root 'users/sessions#new'

    # get 'auth/:provider/callback', to: 'sessions#create'

    scope '/users' do
    
      resources :albums do     
        collection do
          get '/my_album', to: "albums#my_album",as: 'my_album'
          get '/friend_album', to: "albums#friend_album",as: 'friend_album'
        end  
        member do
          delete 'destroy_pic'
        end
        
        resources :comments,only: [:index,:destroy,:new,:create] do
          collection do
            post '/remark', to:'comments#remark', as: 'remark'
            post '/comments_remark', to:'comments#comments_remark', as: 'cmts_remark'
          end
          member do
            delete 'comment_destroy', to: 'comments#comment_destroy', as: 'cmts_destroy'
          end
        end
      end

      resources :friends, only: [:index,:show,:destroy] do
        get :notification
        
        collection do
          get '/:token/accept', to:'friends#accept', as: 'accept'
        end
      end
      post 'friends/search', to:'friends#search'
    end
    resources :dashboards, only: :index
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	
	#Filters 
	before_action :get_friends, only: [:index,:show,:search]

	#Actions
	def index
	end

	def show
	end

	def search
		ids = @friends.ids
		ids = ids.push(current_user.id)
		@results = User.search(params[:q]).all_friends(ids)
	end

	def notification
		@friend = User.find_by(id: params["friend_id"])
		@token = SecureRandom.uuid.gsub(/\-/,'')
		UserMailer.notification(current_user, @friend, @token).deliver_later
		current_userfriend = current_user.user_friends.build(friend_id: @friend.id,token: @token,status: "pending")
		current_userfriend.save
		redirect_to dashboards_path
	end

	def new
	end
	
	def accept
		current_userfriend = UserFriend.find_by(token: params["token"])
		accepted = UserFriend.accepted?(params["token"])
		if accepted #=> make method into model for each status like accepted?, rejectd? ....  current_userfriend.accepted?
			flash[:notice] = "Already added"
		elsif current_userfriend.token == params["token"] && current_user.id == current_userfriend.friend_id
			mutual =  current_user.user_friends.build(token: current_userfriend.token,friend_id: current_userfriend.user_id, status: "accept")
			current_userfriend.status = "accept"
			flash[:notice] = mutual.save && current_userfriend.save ? "Friend Added" : "Could not added"
		else
			flash[:notice] = "Invalid Link"
			redirect_to dashboards_path and return
		end
		redirect_to dashboards_path
	end

	def destroy
		friend = UserFriend.find_by("friend_id = ? AND user_id = ?", params[:id], current_user.id)
		entries = UserFriend.entries_to_be_removed(friend.token)
		entries.destroy_all if entries.present?
		redirect_to friends_path
	end

	def edit
	end

	def update
	end

	private
		def get_friends
			@friends = current_user.friends.confirm_friend
		end
end

app/views/friends/_container.html.erb
<div>
	<table>
		<% results.each do |result| %>
			<tr>
				<td>
		    	<% if result.avater.present? %>
		    		<%= image_tag "/uploads/#{result.avater}", height: '55', width: '70'	%>
		    	<%	end %>			
		    </td>
				<td><%= result.name %></td>
				<td >	
					<%= link_to  friend_notification_path(result.id), class: 'request-sent', remote: true do%>
	  			<i class="fa fa-user-plus " aria-hidden="true"></i>
	  			<% end %>

		  	</td>

		  	<td class="hide-class">
		  		<p >Friend Request Sent</p>
					<% if result.avater.present? %>
					<% end %>
		  	</td>
		  	
			</tr>
		<% end %>
	</table>
</div>

<script type="text/javascript">
	$('.request-sent').click(function(){		
		$(this).closest('tr').find('.hide-class').show()
	});
</script>

app/views/friends/index.html.erb
<div class="row">
	<div class="col-md-2">
		<button type="button" class="btn btn-link" data-toggle="modal" data-target="#search-model">		
			<%= link_to  do%>
	  		<i class="fa fa-plus fa-5x" aria-hidden="true"></i>
	  	<% end %>
	  </button>
	</div>
	
	<div class="col-md-8">
		<h2>Friends</h2>
	</div>
</div>

<!-- Modal -->
	<div id="search-model" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Find Friends</h4>
				</div>
				<div class="modal-body">
					<%= form_tag(url_for(controller: "friends", action: "search"), method: "post", remote: true) do %>
					<p>
						<%= text_field_tag(:q) %>
						<%= submit_tag  "Search" %>
					</p>
					<% end %>

					<div class="popup-container">	
					
					</div>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
<!-- Model end -->
<%@friends.each do |friend|%>
	<div class = 'col-md-6 '>
			<div class='row border-1px'>
				<div class='col-md-4 image'>
					 <% if friend.avatar.present? %>
	    		 <%= image_tag friend.avatar_url, class: 'img-thumbnail'	%>
	    	   <%	end %>
	    	</div>

				<div class='col-md-4 image'>
					<p><%= friend.name	%></p>
				</div>

				<div class='col-md-2'>
					<%= link_to 'Remove Friend', friend_path(friend.id) , method: :delete, data: { confirm: 'Remove Friend?' } ,class: "btn btn-danger btn-sm remove-friend" %>
				</div>
			</div>
	</div>
<% end %>

app/views/friends/search.js.erb
$('.popup-container').html('<%= j render partial: "container",locals: { results: @results} %>');

app/views/friends/show.html.erb
<div class="row">
	<div class="col-md-2">
		<button type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal">		
			<%= link_to  do%>
	  		<i class="fa fa-plus fa-5x" aria-hidden="true"></i>
	  	<% end %>
	  </button>
	</div>
	
	<div class="col-md-8">
		<h2>Friends</h2>
	</div>
</div>

<!-- Modal -->
	<div id="myModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Find Friends</h4>
				</div>

				<div class="modal-body">
					<%= form_tag(url_for(controller: "friends", action: "search"), method: "post", remote: true) do %>
						<p>
							<%= text_field_tag(:q) %>
							<%= submit_tag  "Search" %>
						</p>
					<% end %>

					<div class="popup-container">	
					
					</div>
				</div>
				
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
<!-- Model end -->
<%@friends.each do |friend|%>
	<div class = 'col-md-6 '>
		<div class='row border-1px'>
			<div class='col-md-4 image'>
				 <% if friend.avater.present? %>
    		 <%= image_tag "/uploads/#{friend.avater}", class: 'img-thumbnail'	%>
    	   <%	end %>
    	</div>

			<div class='col-md-4 image'>
				<p><%= friend.name	%></p>
			</div>

			<div class='col-md-2'>
				<%= link_to 'Remove Friend', friend_path(id: friend.id) , method: :delete, data: { confirm: 'Remove Friend?' } ,class: "btn btn-danger btn-sm remove-friend" %>
			</div>
		</div>
	</div>
<% end %>