config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/index'

  #To map with user controller
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/contacts/:provider/contact_callback", to:"dashboards#index"
  get "/contacts/failure", to:"dashboards#failure"


  devise_scope :user do

    # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',passwords: 'users/passwords' }
    root 'users/sessions#new'

    # get 'auth/:provider/callback', to: 'sessions#create'

    scope '/users' do
    
      resources :albums do     
        collection do
          get '/my_album', to: "albums#my_album",as: 'my_album'
          get '/friend_album', to: "albums#friend_album",as: 'friend_album'
        end  
        member do
          delete 'destroy_pic'
        end
        
        resources :comments,only: [:index,:destroy,:new,:create] do
          collection do
            post '/remark', to:'comments#remark', as: 'remark'
            post '/comments_remark', to:'comments#comments_remark', as: 'cmts_remark'
          end
          member do
            delete 'comment_destroy', to: 'comments#comment_destroy', as: 'cmts_destroy'
          end
        end
      end

      resources :friends, only: [:index,:show,:destroy] do
        get :notification
        
        collection do
          get '/:token/accept', to:'friends#accept', as: 'accept'
        end
      end
      post 'friends/search', to:'friends#search'
    end
    resources :dashboards, only: :index
  end
end

app/models/album.rb
class Album < ApplicationRecord
  #Associations
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy, autosave: true
 
  has_many :album_images, dependent: :destroy, autosave: true

  #Scopes
  scope :ordered_desc, -> { order(count: :desc) }
  scope :friends_albums, -> (user_ids) { where(user_id: user_ids) }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	
	before_action :get_friend_albums, only: [:friend_album, :index]
	
	#Actions
	def index	
		@albums = current_user.albums.ordered_desc.paginate(:page => params[:page], :per_page => 5)
		@friends_albums = @friend_albums.paginate(:page => params[:page], :per_page => 5)
	end

  # /album/my
	def my_album
	end

  # /album/friend
	def friend_album
	end
	
	def destroy_pic
		@image = current_user.albums.find_by(id: params[:id]).album_images.find_by(id: params[:pic_id])	
		if @image.destroy
			redirect_to album_path(params[:id])
		else
			redirect_to album_path(params[:id])
		end
	end

	def show
		@album = current_user.albums.find(params[:id])
		@albumimage = AlbumImage.new
	end

	def new
		@album = Album.new
		@album_image = @album.album_images.build
	end

	def create
		@album = current_user.albums.new(params.require(:album).permit(:album_name))
		images = params["album"]["image_name"]
		if images.present?
			images.each do |image|
				@album_image = @album.album_images.build
				@album_image.image_name = image
			 	@album_image.size = image.size
			end			
			if @album.save
				flash[:notice] = "Album Created"
				redirect_to albums_path	
			else
				flash[:notice] = "Album did not create size too large"
				render 'new'
			end
		else
			flash[:notice] = "Album could not uploaded please select atleat one image"
			redirect_to new_album_path	
		end
	end

	def edit
	end
	
	def update
		@album = current_user.albums.find_by(id: params[:id])
		img_names = params["album"]["image_name"] if @album.present?
		if img_names.present?
			img_names.each do |image|
				@album_image = @album.album_images.build
				@album_image.image_name = image		
			 	@album_image.size = image.size
			end
			if @album.save
				redirect_to album_path(params[:id])
			else
				flash[:notice] = "Album did update size too large"
				render 'my_album_all'
			end
		else
			flash[:notice] = "Album could not update"
			redirect_to album_path(params[:id])
		end
	end

	def destroy
		@album = current_user.albums.find_by(id: params[:id])
		flash[:notice] = @album.destroy ? "Album deleted" : "Album could not deleted"
		redirect_to albums_path
	end

	def get_friend_albums
		user_ids = current_user.friends.confirm_friend.ids
		@friend_albums = Album.friends_albums(user_ids).ordered_desc #move it to scope/ :done
	end

	#Private methods
		private
			def album_params
	      params.require(:album).permit(:name,:album_name,:image_name)
	    end
end

app/views/albums/friend_album.html.erb
<div class='row'>
	<div class='col-md-4 col-sm-offset-4'>		
		<h2>Friend-Albums</h2>
	</div>
</div>
<div class='row'>
	<% @friend_albums.each do |album| %>
			<div class='col-md-2'>
				<div class="col-md-4">
					<h4><%= current_user.friends.confirm_friend.find_by(id: album.user_id).name %></h4>
				</div>
				
				<div class='col-md-12'> 
					<%= link_to album_comments_path(album.id) do %>
						<% if album.album_images.first.present? %>
							<%= image_tag album.album_images.first.image_name_url, class: 'img-thumbnail'	%>
						<% else %>
							<%= image_tag "images.png", class: 'img-thumbnail' %>
						<% end %>
					<% end %>
				</div>
				
				<div class="col-md-11 col-sm-offset-1 index-margin-bottom">
					<p><%= link_to album.album_name %></p>
				</div>
			</div>
	<% end %>	
</div>

app/views/albums/index.html.erb
<%= form_for current_user , url: {action: "create"}, method: "post"  do |f| %>
	<div class='row'>
		<div class='col-md-4'>
			<%= link_to new_album_path, title:"Create new album" do%>
		  	<i class="fa fa-plus fa-3x" aria-hidden="true"></i>
		  <% end %>	
		</div>

		<div class='col-md-4'>		
			<h2>Albums</h2>
		</div>

		<div class='col-md-4'>		
			
		</div>		
	</div>

	<div class='row index-margin-bottom'>
		<% @albums.each do |item|%>
			<% image = item.album_images.first %>
			<div class='col-md-2'>
					
				<div class='col-md-1 col-sm-offset-7'>
					<%= link_to album_path(item.id),title:"Add More pic" do%>
		        <span class="glyphicon glyphicon-plus"></span>
		      <% end %>
				</div>

				<div class='col-md-2'>
					<%= link_to album_path(item.id), method: :delete ,title: "Remove Album", data: { confirm: 'Are you sure?' }  do %> 
						<title>Remove</title>
		        <span class="glyphicon glyphicon-remove"></span>
		      <% end %> 	
				</div>

				<div class='col-md-12'>
					<%= link_to album_comments_path(item.id) do %>
						<%= image_tag first_image(item) , class: 'img-thumbnail' %>
					<% end %>
				</div>

				<div class='col-md-12 index-margin-bottom'>
					<p><%= link_to item.album_name %></p>
				</div>
			</div>
		<% end %>
		<div class="col-md-2", style="margin-top: 70px; color: green;">
			<h3><%= link_to "View All", my_album_albums_path %></h3>
		</div>
		<div class="col-md-12">
			<%= will_paginate @albums %>
		</div>
	</div>
<% end %>


<hr>
<div class='row'>
	<div class='col-md-4 col-sm-offset-4'>		
		<h2>Friends-Albums</h2>
	</div>
	
	<div class='col-md-4'>		
	</div>
</div>

<div class='row'>
	<% @friends_albums.each do |album| %>
		<div class='col-md-2'>
			<div class="col-md-4">
				<h4><%= current_user.friends.confirm_friend.find_by(id: album.user_id).name %></h4>
			</div>
			
			<div class='col-md-12'> 
				<%= link_to album_comments_path(album.id) do %>
					<% if album.album_images.first.present? %>
						<%= image_tag album.album_images.first.image_name_url(:size_135_180) , class: 'img-thumbnail'	%>
					<% else %>
						<%= image_tag "images.png", class: 'img-thumbnail' %>
					<% end %>
				<% end %>
			</div>
			<div class="col-md-11 col-sm-offset-1">
				<%= link_to album.album_name %>
			</div>
		</div>
	<% end %>	
	<div class="col-md-2", style="margin-top: 90px; color: green;">
		<h3><%= link_to "View All", friend_album_albums_path %></h3>
	</div>
	<div class="col-md-12">
		<%= will_paginate @albums %>
	</div>
</div>
	

app/views/albums/my_album.html.erb
<%= form_for current_user , url: {action: "create"}, method: "post"  do |f| %>
	<div class='row'>
		<div class='col-md-4'>
			<%= link_to new_album_path, title:"Create new album" do%>
		  	<i class="fa fa-plus fa-3x" aria-hidden="true"></i>
		  <% end %>	
		</div>

		<div class='col-md-4'>		
			<h2>My-Albums</h2>
		</div>
	</div>	

	<div class='row'>
		<% current_user.albums.each do |item|%>
			<% image = item.album_images.first %>
			<div class='col-md-2'>
			
				<% image = item.album_images.first %>	
					<div class='col-md-1 col-sm-offset-7'>
						<%= link_to  album_path(item.id),title:"Add More pic" do%>
			        <span class="glyphicon glyphicon-plus"></span>
			      <% end %>
					</div>
					<div class='col-md-1'>
						<%= link_to album_path(item.id), method: :delete ,title:"Remove Album", data: { confirm: 'Are you sure?' }  do%> 
							<span class="glyphicon glyphicon-remove"></span>
			        
			      <% end %> 	
					</div>
					
					<div class='col-md-12'>
						<%= link_to album_comments_path(item.id) do %>
							<% if item.album_images.first.present? %>
								<%= image_tag item.album_images.first.image_name_url(:size_135_180) , class: 'img-thumbnail' %>
							<% else %>
								<%= image_tag "images.png", class: 'img-thumbnail' %>
							<% end %>
						<% end %>
					</div>
					<div class='col-md-12 index-margin-bottom'>
						<p><%= link_to item.album_name %></p>
					</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/albums/new.html.erb
<%= form_for @album, url: albums_path, method: :post do |f| %>

  <div class="col-md-12 center">
    <h3>Upload album<h3>
  </div>
  
  <div class="col-md-12 center">
    <%= f.label :Album_name %>
    <%= f.text_field :album_name, :required => true %>  
  </div>
  
  <div class="col-md-2 col-sm-offset-4">
    <%= f.label :pictures, :required => true %>
    
  </div>
  <div class="col-md-6 ">
    <%= f.file_field :image_name, multiple: true %>
  </div>
  
  <div class="col-md-12 center">
    <%= f.submit "Save changes" %>
  </div>
  
<% end %>

app/views/albums/show.html.erb
<%= form_for @album , url: album_path(@album.id), method: "put"  do |f| %>
  <div class='row'>
    <div class='col-md-12'>
      <h2><%= @album.album_name %></h2>
    </div>
  </div>
  <hr>
  <div class='row'>
    <div class='col-md-2'>
      Add More Images
    </div>
  
    <div class='col-md-3'>
      <%= f.file_field :image_name, :multiple => true, :required => true %>
    </div>
  
    <div class='col-md-2'>
      <%= f.submit "Update Album" %>
    </div>
  </div>
  <br>
  <hr>
  <div class='row'>
    <% @album.album_images.each do |item|%>
      <div class='col-md-2'>    
        <div class='col-md-1 col-sm-offset-9'>
          <%= link_to destroy_pic_album_path(@album.id,pic_id: item.id),method: :delete, title: "Delete pic",data: { confirm: 'Are you sure?' }  do %>
            <i class="fa fa-trash fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
    
        <div class='col-md-12'>          
          <%= image_tag item.image_name_url if item.image_name.present? %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>