config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/index'

  #To map with user controller
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/contacts/:provider/contact_callback", to:"dashboards#index"
  get "/contacts/failure", to:"dashboards#failure"


  devise_scope :user do

    # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',passwords: 'users/passwords' }
    root 'users/sessions#new'

    # get 'auth/:provider/callback', to: 'sessions#create'

    scope '/users' do
    
      resources :albums do     
        collection do
          get '/my_album', to: "albums#my_album",as: 'my_album'
          get '/friend_album', to: "albums#friend_album",as: 'friend_album'
        end  
        member do
          delete 'destroy_pic'
        end
        
        resources :comments,only: [:index,:destroy,:new,:create] do
          collection do
            post '/remark', to:'comments#remark', as: 'remark'
            post '/comments_remark', to:'comments#comments_remark', as: 'cmts_remark'
          end
          member do
            delete 'comment_destroy', to: 'comments#comment_destroy', as: 'cmts_destroy'
          end
        end
      end

      resources :friends, only: [:index,:show,:destroy] do
        get :notification
        
        collection do
          get '/:token/accept', to:'friends#accept', as: 'accept'
        end
      end
      post 'friends/search', to:'friends#search'
    end
    resources :dashboards, only: :index
  end
end

app/views/layouts/[LAYOUT_NAME].html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Albumapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Albumapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/actions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albumapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= yield %>
		<div class = "topright">
		</div>	  
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyD5oYhkOFBVuAqPGcqtheI1WehY5KxpXeA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

  <body>
    <% if current_user.present? %>
      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
        
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to "Albumapp",dashboards_path, class: "navbar-brand" %>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <% if current_user.avatar.present? %>
              <li><a><%= image_tag current_user.avatar_url, height: "30px",width: "40px" %></a></li>
              <% end %>
              <%if current_user.present?%>
                <li><%= link_to current_user.name,edit_user_registration_path %></li>
              <% end %>
              <li><%= link_to "Manage Album", albums_path  %></li>
              <li><%= link_to 'Friends', friends_path %></li>
              <li><%= link_to 'Edit Info', edit_user_registration_path %></li>
              
              <li></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    
    <div class="container min-height">    
      <div class="col-lg-12">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>

        <% end %>
        
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div> 
      
      <div class = "col-md- 12">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% elsif controller_name != 'registrations' && controller_name != 'passwords' %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", "javascript:void(0);", :class => 'navbar-link', data: { toggle: "modal", target: '#mylogin'} %>
          <% end %>
        </p>
      </div>
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>

    <footer>
        <p>&copy; Company 2017</p>
    </footer>

  </body>
</html>

app/views/layouts/demo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albumapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>	
    
		<%= yield %>
		<div class = "header">
      <div style="position: fixed; ">
      <%= link_to dashboards_path do %>
      <%= image_tag "/uploads/albumapp.jpeg", size: "70x70" %>
      <% end %>  
      </div>
      <div style="margin-left: 15px;">
        <ul>
          <li><%= link_to 'Manage Album', albums_path %></li>
          <li><%= link_to 'Friends', friend_path(id: @user.id) %></li>
          <li><%= link_to 'Edit Info', edit_user_path(id: @user.id) %></li>
          <li><%= link_to 'LogOut', actions_logout_path, method: :delete %></li>
        </ul>
      </div>
      
      
    </div> 
    <div class = "footer">
      <p>about</p>
      <p>contact us</p>
    </div>    
  </body>
</html>